### ISSUE TITLE
Update all  metadata terms in both the Rules and the Profile text (if necessary) 

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/ldac-profile#8]
Work on a branch called great-metadata-migation

Use this spreadsheet to keep track of what has been done: https://docs.google.com/spreadsheets/d/1_SQkLlKcQqMIZ97VeoExgByNje6yRqYqZL-F53PSfwM/edit#gid=0

**Comment by ptsefton** [comment]
@rosanna-smith 

- Work on the great-metadata-migration branch
- Change the [profile generation script](https://github.com/Language-Research-Technology/ldac-profile/blob/great-metadata-migration/make-profile.js) to work like the one in the [software profile](https://github.com/ResearchObject/software-profiles/blob/software_source_code_crate-dev/make-profile.js)
  - Will need to install the ro-crate-editor-profiles from github 
  - Copy and adapt the script from the software profiles
- In the profile text/template change the rules so they are coming from the mode file as per the way it works in the software profile
-

**Comment by rosanna-smith** [comment]
The software profile link above doesn't work for me - I can get as far as https://github.com/ResearchObject

**Comment by rosanna-smith** [comment]
Have installed ro-crate-editor-profiles to ldac-profile in the great-metadata-migration (haven't committed). Also updated make-profile.js to be more in line with how the software profiles one works. Have had a play around with the /profile-text/profile.md and /templates/profile.md files, but will need to work through this part more with someone because I don't understand it fully and my changes don't seem to be affecting the /profile/profile.md file.

**Comment by rosanna-smith** [comment]
Newer updates to the profile.md in this issue: https://github.com/Language-Research-Technology/ldac-profile/issues/13
Closing this one.
